### PR TITLE
minor cleanups

### PR DESCRIPTION
**Pull request by toppk**
just starting to use your library, and i found some minor issues, so I thought I'd quickly shoot them over your way.  haven't actually used the library yet, but looks good so far :)

these should be straight forward changes, happy to explain further if needed.

### CODE REVIEW

**Comment by paulokuong** [comment]
@toppk thanks will take a look

**Comment by toppk** [comment]
okay.  just switch the import to absolute to the style used elsewhere.

**Comment by paulokuong** [comment]
@toppk thanks

**Comment by a-d-collins** [comment]
@paulokuong @pkuong the tar.gz contents available on pypi for version 0.1.17 of this package (https://pypi.org/project/noaa-sdk/0.1.17/#files) do not match those of the master branch that resulted from merging this pull-request. Do you have plans to release that soon? In python 3.73 envs I get dependency errors that relate to requests 2.21 (which was changed in this branch).

Also, it looks like Requests 2.22.0 dropped support for python 3.4 (https://2.python-requests.org/en/master/community/updates/#id1), so if you need help when it comes to supporting 3.73, let me know.

**Pull request merged**
